# 01. Знакомство с `torch.Tensor`

V 0.1 04.02.2021

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [ ]:
import torch
import numpy as np

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [ ]:
tns = torch.zeros(8, 8)
tns[0] = torch.tensor([-4, -3, -2, -6, -5, -2, -3, -4])
tns[-1 : ]= abs(tns[0])
tns[-2], tns[1] = torch.ones(8), torch.ones(8)*-1
tns 

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [ ]:
x = torch.arange(2, 21, 2)
x

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
y = x*(x+1)
y

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [ ]:
x = torch.arange(1,8)
y = torch.arange(0, 101, 10).reshape(11,1)
x

tensor([1, 2, 3, 4, 5, 6, 7])

In [ ]:
y

tensor([[  0],
        [ 10],
        [ 20],
        [ 30],
        [ 40],
        [ 50],
        [ 60],
        [ 70],
        [ 80],
        [ 90],
        [100]])

In [ ]:
mtx = x+y
mtx

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [ ]:
# repeat - повторяет  тензор вдоль заданных размеров
def tensor_func(n, m):
  t = torch.tensor([[0, 1], [2, 3]])
  t = t.repeat(n, m)[:n:, :m:]
  return t

In [ ]:
tensor_func(4, 5)

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

In [ ]:
buf = torch.rand((4, 7)) * 20
res = buf/(buf.max()-buf.min())-buf.min()/(buf.max()-buf.min())
res

tensor([[0.5982, 0.4885, 0.4201, 0.7364, 0.9548, 0.0899, 1.0000],
        [0.1365, 0.3418, 0.0000, 0.2886, 0.6127, 0.9671, 0.3842],
        [0.3109, 0.7353, 0.5312, 0.0629, 0.9117, 0.7216, 0.1861],
        [0.1925, 0.9685, 0.7058, 0.8143, 0.4499, 0.9054, 0.3762]])

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [ ]:
ar1 = 10 * torch.rand(4, 7)
ar2 = 10 * torch.rand(4, 7)
x = torch.max(ar1, ar2)
x

tensor([[5.7598, 5.0122, 9.0708, 4.1353, 5.5558, 9.5721, 5.7621],
        [6.4396, 9.8189, 8.8414, 4.2629, 4.4012, 4.1044, 2.6308],
        [8.1378, 9.5884, 3.8456, 9.1235, 5.1774, 5.1524, 8.6486],
        [5.1934, 9.4299, 2.4470, 1.1700, 2.6674, 7.0994, 9.1246]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [ ]:
x = torch.randint(100, (20,))
print(x)
print("Второе сверху значение:", torch.topk(x, 2)[0][1].item())
print("Индекс:", torch.topk(x, 2)[1][1].item())

tensor([68, 14, 21, 99, 96, 30, 17, 79, 10, 20, 77,  2, 66,  3, 17, 88, 70, 91,
        57, 19])
Второе сверху значение: 96
Индекс: 4


## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [ ]:
first_items = torch.arange(1, 8, step=1)
print(first_items)
second_items = torch.arange(0, 101, step=10).reshape(-1, 1) #Преобразуем в столбец из строки
print(second_items)
first_items + second_items

tensor([1, 2, 3, 4, 5, 6, 7])
tensor([[  0],
        [ 10],
        [ 20],
        [ 30],
        [ 40],
        [ 50],
        [ 60],
        [ 70],
        [ 80],
        [ 90],
        [100]])


tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [ ]:
a_2d = torch.Tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.Tensor([1,2,3])

a_2d = torch.transpose(a_2d, 0, 1)

tens = torch.sub(a_2d, b_1d)
tens

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [ ]:
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])

res = (a == b).nonzero(as_tuple=True)
res[0].numpy()

array([1, 3, 5, 7])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [ ]:
arr = torch.arange(9).view(3,3)
arr = arr.flip(1).flip(0).numpy()
arr

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [ ]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
mask = (a >= 5) & (a <= 10)
res = a[mask].numpy()
res

array([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2 тензора `np.arange(9).reshape(3,3)`

In [ ]:
res = torch.arange(9).reshape(3,3)
print(res)
res = res[:, [0, 2, 1]]
res

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([[0, 2, 1],
        [3, 5, 4],
        [6, 8, 7]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
t = torch.randint(0, 11, (8, 10))
t

tensor([[ 7,  5,  0, 10,  7,  3,  1,  5,  3,  5],
        [ 0,  1, 10,  0,  1,  0,  0,  8,  5,  9],
        [ 8,  6,  2,  1,  2,  0,  1,  2,  3,  4],
        [ 6,  3,  4,  2,  8,  2,  2,  2,  1,  1],
        [ 4, 10,  5,  4,  9,  7, 10,  3,  2,  8],
        [ 9,  8,  9, 10,  1, 10,  3,  7,  4,  5],
        [ 3,  4,  6,  0,  9,  0,  2,  5,  6,  6],
        [ 2,  2,  6,  0,  6,  7,  4,  2,  0,  5]])

In [ ]:
t.sum(dim=1).argmin() #индекс

tensor(2)

In [ ]:
t.sum(dim=1).min(dim=0) #индекс

torch.return_types.min(
values=tensor(29),
indices=tensor(2))

In [ ]:
t[t.sum(dim=1).argmin()] #строчка

tensor([8, 6, 2, 1, 2, 0, 1, 2, 3, 4])

1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [ ]:
res = torch.randint(0, 101, size=[20])
print(res)
#Все что меньше - режем
res[(res < 30)] = 30
print(res)
#Все что больше - режем
res[(res > 70)] = 70
res

tensor([ 79,  77,  30,  28,  35,  53,  97,  66,  18,   1, 100,   1,  74,  40,
         34,  42,  78,  20,  42,  87])
tensor([ 79,  77,  30,  30,  35,  53,  97,  66,  30,  30, 100,  30,  74,  40,
         34,  42,  78,  30,  42,  87])


tensor([70, 70, 30, 30, 35, 53, 70, 66, 30, 30, 70, 30, 70, 40, 34, 42, 70, 30,
        42, 70])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [ ]:
a1 = torch.randint(0, 11, size=[30, 3])
a2 = torch.randint(0, 11, size=[30, 3])

mask = a1 > a2
print(a1[mask])

res = a1[mask].sum().item()
print("Sum:", res)

tensor([10, 10,  9,  5, 10,  9,  6,  7,  6,  7, 10,  7,  3,  5, 10,  5,  7,  9,
         3,  4,  3,  8,  5,  2,  9,  8,  9,  9,  2,  6,  9,  5, 10,  7,  7,  6,
        10,  3,  2,  8,  6])
Sum: 276


1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [ ]:
t = torch.randint(11, (20, 20))
t

tensor([[ 7,  2,  1,  2,  0,  6,  2,  0,  2,  4,  8,  1,  4,  8,  7,  5,  6,  3,
          1, 10],
        [ 1,  0,  8,  0,  3,  5,  9,  0,  0, 10,  8,  1,  7,  9,  1,  8,  6,  5,
          2, 10],
        [ 2,  5,  5,  9,  1,  2,  9,  0,  0,  9,  7,  3,  9,  0,  4,  6,  6,  9,
          2,  0],
        [ 2,  4,  0, 10,  3,  6,  2,  3, 10,  8,  4,  8,  9,  1,  4,  9,  8,  8,
          8,  8],
        [10,  4,  2,  7,  1,  4,  3,  2,  4,  3,  5,  8,  2,  9,  5,  6,  4,  2,
          4,  9],
        [ 6,  4,  2, 10,  2,  2,  7,  1,  7, 10,  2, 10,  9,  8,  0,  9,  9, 10,
          4,  9],
        [ 7, 10,  8,  7,  3,  5,  4,  5,  4,  4,  7,  6,  1,  5,  0,  5,  3,  8,
          2,  7],
        [ 3,  3,  9,  5,  6,  6,  3,  6,  7,  2,  1,  4, 10,  7,  7,  3,  1,  9,
          2,  2],
        [ 9,  6,  1,  9,  9,  6, 10,  7,  4,  7,  8, 10,  9,  6,  9,  1,  5,  1,
          1, 10],
        [ 7,  0,  9,  8,  4, 10,  3,  7, 10,  9,  3,  2,  0,  9,  7,  0,  7,  8,
          7,  0],
        [ 

In [ ]:
rows = torch.arange(19)
columns = torch.arange(1,20)
t[rows, columns]

tensor([ 2,  8,  9,  3,  4,  7,  5,  7,  7,  3, 10,  5,  5,  4,  9,  8,  8, 10,
         0])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [ ]:
ar1 = torch.randint(11, (5, 10))
ar2 = torch.randint(11, (5, 10))
print(ar1)
print()
print(ar2)

tensor([[ 5,  7, 10,  3,  4,  0,  9,  0,  2,  2],
        [ 6,  7,  4,  3,  0,  7,  1,  5,  3,  2],
        [ 7,  5,  4,  9,  0,  3,  9,  6,  9,  9],
        [ 6,  4,  2, 10,  1,  0,  6,  4,  3,  5],
        [ 1, 10,  0,  7,  6,  3,  9,  4, 10,  7]])

tensor([[ 0,  2,  6,  4,  4,  3,  2,  5,  0, 10],
        [ 0,  5,  1,  7,  8,  1,  9,  6,  4,  3],
        [ 8,  6,  7,  0,  2,  5,  5,  7,  3,  8],
        [ 7,  9,  0,  5,  6, 10,  7,  6,  4,  0],
        [ 9,  0, 10,  0,  8,  7, 10,  8,  5,  6]])


In [ ]:
ar1[ar1 == ar2] *= 2
ar1

tensor([[ 5,  7, 10,  3,  8,  0,  9,  0,  2,  2],
        [ 6,  7,  4,  3,  0,  7,  1,  5,  3,  2],
        [ 7,  5,  4,  9,  0,  3,  9,  6,  9,  9],
        [ 6,  4,  2, 10,  1,  0,  6,  4,  3,  5],
        [ 1, 10,  0,  7,  6,  3,  9,  4, 10,  7]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [ ]:
ar1 = torch.randint(11, (4, 7))
ar2 = torch.randint(11, (4, 7))
ar3 = torch.randint(11, (4, 7))
print(ar1)
print()
print(ar2)
print()
print(ar3)

tensor([[ 0,  7, 10,  9,  6,  6,  3],
        [ 7,  4,  1,  6,  1,  2, 10],
        [ 7,  3,  5,  1,  4,  0,  5],
        [ 1,  9,  6,  7,  5,  0,  1]])

tensor([[ 2,  0,  2,  7,  7, 10,  5],
        [ 0,  7,  9,  7,  6,  1,  1],
        [ 1,  3,  8,  3,  1,  5,  9],
        [ 8,  0,  2, 10, 10,  4,  5]])

tensor([[ 6,  3,  7,  4,  2,  7,  6],
        [ 8,  5,  6,  2, 10,  2,  3],
        [ 0,  6,  6,  6,  9,  4,  3],
        [ 2, 10,  3,  0,  4,  4,  3]])


In [ ]:
ar1[(ar1 > ar2) & (ar1 < ar3)] = 0 
ar1

tensor([[ 0,  7, 10,  9,  6,  6,  3],
        [ 0,  4,  1,  6,  1,  2, 10],
        [ 7,  3,  5,  1,  0,  0,  5],
        [ 1,  0,  6,  7,  5,  0,  1]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [ ]:
a1 = torch.randint(0, 21, size=(20, 5))
print(a1, "\n")
condition = (a1.T == a1.max(axis=1).values).T.sum(axis=0) > 5
res = (condition).nonzero(as_tuple=True)
res[0]

tensor([[ 1,  7, 14, 16, 10],
        [ 0,  9,  6, 20, 11],
        [19, 19,  2, 12, 19],
        [ 0,  0, 10,  7,  9],
        [ 2,  1, 12,  5,  7],
        [ 1,  7, 14, 20, 18],
        [ 9, 19,  1,  1, 18],
        [13, 20, 14, 14,  9],
        [ 6, 19,  9, 17,  1],
        [14, 14,  8, 15,  0],
        [14,  7, 17, 13,  8],
        [ 4, 13, 15, 13, 14],
        [ 5, 12, 18,  0, 16],
        [ 5,  7,  5, 18,  7],
        [ 4,  7, 15, 13, 14],
        [20,  2, 20, 12,  6],
        [ 2, 11, 14,  1,  2],
        [13, 16,  7, 13, 13],
        [ 3,  1,  6,  1,  5],
        [ 2,  6,  9, 11, 14]]) 



tensor([2])

1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

In [ ]:
ar1 = torch.rand((4, 7))
print(ar1)
maximum = ar1.max().item()
print(maximum)

ar1[(ar1 == maximum).nonzero(as_tuple=True)[0][0] + 1:, (ar1 == maximum).nonzero(as_tuple=True)[1][0] + 1:] = 0
ar1

tensor([[0.0996, 0.7655, 0.5749, 0.7991, 0.8741, 0.0752, 0.4333],
        [0.2060, 0.7965, 0.9568, 0.3966, 0.7007, 0.7827, 0.5314],
        [0.9188, 0.1836, 0.2938, 0.9920, 0.6280, 0.1310, 0.2614],
        [0.9234, 0.6579, 0.0954, 0.6366, 0.1418, 0.9083, 0.5201]])
0.9919907450675964


tensor([[0.0996, 0.7655, 0.5749, 0.7991, 0.8741, 0.0752, 0.4333],
        [0.2060, 0.7965, 0.9568, 0.3966, 0.7007, 0.7827, 0.5314],
        [0.9188, 0.1836, 0.2938, 0.9920, 0.6280, 0.1310, 0.2614],
        [0.9234, 0.6579, 0.0954, 0.6366, 0.0000, 0.0000, 0.0000]])

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [ ]:
arr = torch.tensor([2, 3, 2, 2, 2, 1])
res = torch.zeros(arr.size()[0], arr.max())
res[torch.arange(arr.size()[0]), arr-1] = 1
res

tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая. 

In [ ]:
arr = torch.randint(0, 101, size=[20])
print(arr)
most_value = torch.mode(arr)[0]
print(most_value)
res = (arr == most_value).nonzero(as_tuple=True)[0].tolist()
res

tensor([ 77,   4,  49,  67,  27,  68,  52,  14,  14,  30,  85,  82,  42,  29,
         89,  91,  72,  60,  81, 100])
tensor(14)


[7, 8]

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [ ]:
x = torch.linspace(0, 10, steps=10000000)
x

tensor([0.0000e+00, 1.0000e-06, 2.0000e-06,  ..., 1.0000e+01, 1.0000e+01,
        1.0000e+01])

In [ ]:
interval = x[(torch.sin(x) * x) > 0.5]
interval

tensor([0.7408, 0.7408, 0.7408,  ..., 9.3714, 9.3714, 9.3714])

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [ ]:
t = torch.arange(2, 101)
t

tensor([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
         16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
         30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
         44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
         72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
         86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
        100])

In [ ]:
for p in t:
  if p != 0:
    t[2*p-2::p] = 0
    
t

tensor([ 2,  3,  0,  5,  0,  7,  0,  0,  0, 11,  0, 13,  0,  0,  0, 17,  0, 19,
         0,  0,  0, 23,  0,  0,  0,  0,  0, 29,  0, 31,  0,  0,  0,  0,  0, 37,
         0,  0,  0, 41,  0, 43,  0,  0,  0, 47,  0,  0,  0,  0,  0, 53,  0,  0,
         0,  0,  0, 59,  0, 61,  0,  0,  0,  0,  0, 67,  0,  0,  0, 71,  0, 73,
         0,  0,  0,  0,  0, 79,  0,  0,  0, 83,  0,  0,  0,  0,  0, 89,  0,  0,
         0,  0,  0,  0,  0, 97,  0,  0,  0])

In [ ]:
t[t != 0] # простые числа в пределах ста

tensor([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
        67, 71, 73, 79, 83, 89, 97])

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [ ]:
x = torch.tensor([2, 3, 4, 5, 6, 7, 8, 9, 10])
y = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


res = ((x - y) ** 2).sum().item()
res

9

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [ ]:
arr = torch.randint(0, 101, size=[20, 3])
print(arr,"\n")

mask = (arr ** 2).sum(axis=1).sort().indices
print("mask:\n",mask)
res = arr[mask]
res

tensor([[ 48,  66,  78],
        [ 73,  62,  78],
        [ 67,  95,  92],
        [ 96,  95,  45],
        [ 76,  42,  80],
        [  3,  38,  86],
        [ 43,  17,  41],
        [ 70,  46,  25],
        [ 87,  35,  93],
        [  6,  86,  99],
        [ 76,   1,  62],
        [ 23, 100,  76],
        [ 97,  97,  76],
        [ 89,  53,  16],
        [ 31,  36,  63],
        [ 44,  75,  40],
        [  0,  31,  32],
        [ 40,   9,  28],
        [ 61,  22,  91],
        [ 19,  27,  99]]) 

mask:
 tensor([16, 17,  6, 14,  7,  5, 15, 10, 19, 13, 18,  0,  4,  1, 11,  9,  8,  3,
         2, 12])


tensor([[  0,  31,  32],
        [ 40,   9,  28],
        [ 43,  17,  41],
        [ 31,  36,  63],
        [ 70,  46,  25],
        [  3,  38,  86],
        [ 44,  75,  40],
        [ 76,   1,  62],
        [ 19,  27,  99],
        [ 89,  53,  16],
        [ 61,  22,  91],
        [ 48,  66,  78],
        [ 76,  42,  80],
        [ 73,  62,  78],
        [ 23, 100,  76],
        [  6,  86,  99],
        [ 87,  35,  93],
        [ 96,  95,  45],
        [ 67,  95,  92],
        [ 97,  97,  76]])

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

In [ ]:
arr = torch.tensor([1, 3, 7, 10, 2, 6, 10, 1])
print(arr)

a = torch.diff(arr)[:-1]
print(a)
b = torch.diff(arr.flip(0)).flip(0)[ 1:]
print(b)

print(((a > 0) & (b > 0)).nonzero( as_tuple= True)[0] + 1)

tensor([ 1,  3,  7, 10,  2,  6, 10,  1])
tensor([ 2,  4,  3, -8,  4,  4])
tensor([-4, -3,  8, -4, -4,  9])
tensor([3, 6])


1.4.6 Задан произвольный массив torch (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [ ]:
t = torch.rand(100)
t

tensor([0.0716, 0.9270, 0.6044, 0.3370, 0.5429, 0.7933, 0.9674, 0.8162, 0.5141,
        0.4160, 0.7041, 0.3621, 0.9100, 0.6412, 0.5583, 0.4085, 0.6969, 0.0169,
        0.8293, 0.1934, 0.7445, 0.3698, 0.5144, 0.8878, 0.6623, 0.3602, 0.8807,
        0.3242, 0.1666, 0.0123, 0.7293, 0.4500, 0.5961, 0.3782, 0.4000, 0.4969,
        0.3932, 0.0303, 0.5758, 0.6440, 0.9352, 0.3990, 0.5478, 0.7469, 0.6054,
        0.5666, 0.3144, 0.0596, 0.5608, 0.3584, 0.6410, 0.1659, 0.0790, 0.0738,
        0.8566, 0.0972, 0.3140, 0.6924, 0.2949, 0.6060, 0.8148, 0.7343, 0.3752,
        0.6304, 0.5714, 0.5512, 0.3890, 0.0228, 0.1911, 0.8863, 0.8078, 0.2421,
        0.0460, 0.4530, 0.2244, 0.0058, 0.8806, 0.7302, 0.4098, 0.6909, 0.3214,
        0.2515, 0.3644, 0.6051, 0.8355, 0.9349, 0.2414, 0.0224, 0.3838, 0.4820,
        0.7456, 0.1376, 0.9239, 0.5392, 0.8075, 0.0686, 0.1210, 0.5871, 0.5626,
        0.7348])

In [ ]:
number = float(input('Введите число: '))

Введите число: 0.5


In [ ]:
max = t[t >= number].sort()
max

torch.return_types.sort(
values=tensor([0.5141, 0.5144, 0.5392, 0.5429, 0.5478, 0.5512, 0.5583, 0.5608, 0.5626,
        0.5666, 0.5714, 0.5758, 0.5871, 0.5961, 0.6044, 0.6051, 0.6054, 0.6060,
        0.6304, 0.6410, 0.6412, 0.6440, 0.6623, 0.6909, 0.6924, 0.6969, 0.7041,
        0.7293, 0.7302, 0.7343, 0.7348, 0.7445, 0.7456, 0.7469, 0.7933, 0.8075,
        0.8078, 0.8148, 0.8162, 0.8293, 0.8355, 0.8566, 0.8806, 0.8807, 0.8863,
        0.8878, 0.9100, 0.9239, 0.9270, 0.9349, 0.9352, 0.9674]),
indices=tensor([ 6, 14, 47,  2, 23, 36, 10, 27, 50, 26, 35, 20, 49, 19,  1, 42, 25, 31,
        34, 28,  9, 21, 16, 41, 30, 11,  7, 18, 40, 33, 51, 13, 45, 24,  3, 48,
        38, 32,  5, 12, 43, 29, 39, 17, 37, 15,  8, 46,  0, 44, 22,  4]))

In [ ]:
min = t[t <= number].sort()
min

torch.return_types.sort(
values=tensor([0.0058, 0.0123, 0.0169, 0.0224, 0.0228, 0.0303, 0.0460, 0.0596, 0.0686,
        0.0716, 0.0738, 0.0790, 0.0972, 0.1210, 0.1376, 0.1659, 0.1666, 0.1911,
        0.1934, 0.2244, 0.2414, 0.2421, 0.2515, 0.2949, 0.3140, 0.3144, 0.3214,
        0.3242, 0.3370, 0.3584, 0.3602, 0.3621, 0.3644, 0.3698, 0.3752, 0.3782,
        0.3838, 0.3890, 0.3932, 0.3990, 0.4000, 0.4085, 0.4098, 0.4160, 0.4500,
        0.4530, 0.4820, 0.4969]),
indices=tensor([36, 11,  5, 42, 30, 17, 33, 20, 46,  0, 24, 23, 25, 47, 45, 22, 10, 31,
         6, 35, 41, 32, 39, 27, 26, 19, 38,  9,  1, 21,  8,  3, 40,  7, 28, 13,
        43, 29, 16, 18, 14,  4, 37,  2, 12, 34, 44, 15]))

In [ ]:
max = max[0][0]
min = min[0][-1]
print(max, min)

tensor(0.5141) tensor(0.4969)


In [ ]:
difference_max = max - number
difference_min = number - min
print('Число наиболее близкое к заданному:')
if difference_max > difference_min:
  print(min)
else:
  print(max)

Число наиболее близкое к заданному:
tensor(0.4969)


1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

**X = A^-1·(-C)·B^-1**

In [ ]:
a = torch.tensor([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]) * 1.0
b = torch.tensor([[3, -1], [2, 1]]) * 1.0
c = torch.tensor([[7, 21], [11, 8], [8, 4]]) * 1.0
print(a)
print()
print(b)
print()
print(c)

tensor([[-1.,  2.,  4.],
        [-3.,  1.,  2.],
        [-3.,  0.,  1.]])

tensor([[ 3., -1.],
        [ 2.,  1.]])

tensor([[ 7., 21.],
        [11.,  8.],
        [ 8.,  4.]])


In [ ]:
a = torch.inverse(a)
b = torch.inverse(b)
x = a @ (-c) @ b
x.round()

tensor([[ 1., -0.],
        [-2.,  1.],
        [ 3., -4.]])

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

In [ ]:
#Система векторов является линейно зависимой тогда и только тогда, 
#когда в ней найдется вектор, который линейно выражается через остальные векторы этой системы
res_dict = {0: "Вектора линейно зависимы", 1: "Вектора линейно независимы"}
a1 = [3., -3, 0, 7]
a2 = [2, 2, 4, 7]
a3 = [1, 2, 3, 4]
a4 = [5, -4, 1, 3]

res = torch.tensor([a1, a2, a3, a4])
res_dict[int(res.det().round().tolist())]

'Вектора линейно зависимы'

In [ ]:
a1 = [1.,1.,1.]
a2 = [1.,2.,0.]
a3 = [0.,-1.,1.]

res = torch.tensor([a1, a2, a3])
res_dict[int(res.det().round().tolist())]

'Вектора линейно зависимы'

In [ ]:
a1 = [1.,1.,1.]
a2 = [1.,2.,0.]
a3 = [0.,-1.,2.]

res = torch.tensor([a1, a2, a3])
res_dict[int(res.det().round().tolist())]

'Вектора линейно независимы'

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 